In [4]:
'''
1. What is a Python library? Why do we use Python libraries?

A Python library is a reusable chunk of code that you may want to include in your programs/ projects. Technically, it is a collection of modules,
 which are Python files with a .py extension, that consist of functions, classes, and variables. A library can also include runnable code.

Python libraries are used for several reasons:

Code Reusability: We use libraries so that we don’t have to write the code from scratch every time. If the task is common and generic, like reading a CSV file, we can use the code that’s already written and tested in the form of a library.
Efficiency: Libraries often have more efficient implementations for complex algorithms and tasks. They are usually optimized for performance, so using a library function can make your code run faster.
Community Support: Python libraries are often open-source and have a community of developers maintaining and improving them. This means they are more reliable and up-to-date.
Simplifying Complex Tasks: Libraries can abstract away difficult tasks or complex implementations. For example, sending an HTTP request is a single function call in the requests library.
Some of the popular Python libraries include numpy for numerical computations, pandas for data manipulation, matplotlib for plotting, scikit-learn for machine learning, and many more.
'''

'\n1. What is a Python library? Why do we use Python libraries?\n\nA Python library is a reusable chunk of code that you may want to include in your programs/ projects. Technically, it is a collection of modules,\n which are Python files with a .py extension, that consist of functions, classes, and variables. A library can also include runnable code.\n\nPython libraries are used for several reasons:\n\nCode Reusability: We use libraries so that we don’t have to write the code from scratch every time. If the task is common and generic, like reading a CSV file, we can use the code that’s already written and tested in the form of a library.\nEfficiency: Libraries often have more efficient implementations for complex algorithms and tasks. They are usually optimized for performance, so using a library function can make your code run faster.\nCommunity Support: Python libraries are often open-source and have a community of developers maintaining and improving them. This means they are more r

In [5]:
#2. What is the ^ifference between Numpy array an^ List?
'''
A NumPy array and a Python list are both used for storing data, but they have some key differences:

Data Homogeneity: NumPy arrays are homogeneous and store data of the same type12. Python lists, on the other hand, are heterogeneous and can store data of different types12.
Memory Usage: NumPy arrays are more memory-efficient as they directly store the data, while Python lists store references to the data2. This makes NumPy arrays faster for numerical computations12.
Size Mutability: You can append elements to a Python list, but you can’t change the size of a NumPy array without making a full copy34.
Operations: Element-wise operations are possible with NumPy arrays but not with Python lists1. Also, NumPy arrays have many built-in functions for scientific computing1.
Dimensionality: Python lists are by default 1-dimensional, but you can create an N-Dimensional list. NumPy arrays can be multi-dimensional1.
'''

'\nA NumPy array and a Python list are both used for storing data, but they have some key differences:\n\nData Homogeneity: NumPy arrays are homogeneous and store data of the same type12. Python lists, on the other hand, are heterogeneous and can store data of different types12.\nMemory Usage: NumPy arrays are more memory-efficient as they directly store the data, while Python lists store references to the data2. This makes NumPy arrays faster for numerical computations12.\nSize Mutability: You can append elements to a Python list, but you can’t change the size of a NumPy array without making a full copy34.\nOperations: Element-wise operations are possible with NumPy arrays but not with Python lists1. Also, NumPy arrays have many built-in functions for scientific computing1.\nDimensionality: Python lists are by default 1-dimensional, but you can create an N-Dimensional list. NumPy arrays can be multi-dimensional1.\n'

In [ ]:
'''
#3. Fin^ the shape, size an^ ^imension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
'''

Shape: (3, 4)
Size: 12
Dimension: 2
'''

In [7]:
'''
#4. Write python co^e to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
'''
# First, let's define the array
array = [[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10, 11, 12]]

# Access the first row
first_row = array[0]

print(first_row)


[1, 2, 3, 4]


In [8]:
'''
#5. How ^o you access the element at the thir^ row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
'''
import numpy as np

# Define the array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Access the element at the third row and fourth column
element = array[2, 3]

print(element)


12


In [9]:
#6 How can you generate a random 3x3 matrix with values between 0 and 1?
import numpy as np

# Generate a 3x3 matrix with random values between 0 and 1
matrix = np.random.rand(3, 3)

print(matrix)


[[0.53529205 0.32969975 0.0343304 ]
 [0.58896495 0.14588118 0.55508061]
 [0.38406914 0.87576908 0.5074963 ]]


In [10]:
#8. Describe the difference between np.random.rand and np.random.randn?
'''
The main difference between np.random.rand and np.random.randn lies in the probabilistic distribution each number is drawn from12:

np.random.rand generates random values from a uniform distribution over the interval [0, 1)12. In a uniform distribution, all values within the given interval are equally likely to be drawn2.
np.random.randn generates samples from the standard normal (Gaussian) distribution12. In a standard normal distribution, values are more likely to be closer to the mean (which is 0 in this case), and the spread of values is determined by the standard deviation (which is 1 in this case)2.
These different distributions can have significant effects on the behavior of algorithms, particularly in fields like machine learning1. For example, initializing weights in a neural network with values from a standard normal distribution (using np.random.randn) often leads to better results than using a uniform distribution (using np.random.rand
'''

'\nThe main difference between np.random.rand and np.random.randn lies in the probabilistic distribution each number is drawn from12:\n\nnp.random.rand generates random values from a uniform distribution over the interval [0, 1)12. In a uniform distribution, all values within the given interval are equally likely to be drawn2.\nnp.random.randn generates samples from the standard normal (Gaussian) distribution12. In a standard normal distribution, values are more likely to be closer to the mean (which is 0 in this case), and the spread of values is determined by the standard deviation (which is 1 in this case)2.\nThese different distributions can have significant effects on the behavior of algorithms, particularly in fields like machine learning1. For example, initializing weights in a neural network with values from a standard normal distribution (using np.random.randn) often leads to better results than using a uniform distribution (using np.random.rand\n'

In [11]:
'''
9. Write co^e to increase the ^imension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
'''
import numpy as np

# Define the array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Increase the dimension of the array
array_new = array[np.newaxis, :]

print(array_new.shape)


(1, 3, 4)


In [12]:
''''
10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
'''

import numpy as np

# Define the array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Transpose the array
array_transposed = array.T

print(array_transposed)


[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [16]:
'''
11. Consi^er the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python1
,+ I(dex wiLe multiplicatio'
]+ Matix multiplicatio'
+ Add both the maticK
-+ Subtact matix B om
+ Diide Matix B by A
     '''

import numpy as np

# Define the matrices
A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Element-wise multiplication
elementwise_product = np.multiply(A2, B2)

# Matrix multiplication
matrix_product = np.dot(A2, B2)

# Addition of both matrices
sum_of_matrices = np.add(A2, B2)

# Subtraction of matrix B from A
difference = np.subtract(A2, B2)

# Division of matrix B by A
division = np.divide(B2, A2)

print("Element-wise multiplication:\n", elementwise_product)
print("Matrix multiplication:\n", matrix_product)
print("Addition of both matrices:\n", sum_of_matrices)
print("Subtraction of matrix B from A:\n", difference)
print("Division of matrix B by A:\n", division)


ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [18]:
'''
11. Consi^er the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python1
,+ I(dex wiLe multiplicatio'
]+ Matix multiplicatio'
+ Add both the maticK
-+ Subtact matix B om
+ Diide Matix B by A
     '''

import numpy as np

# Define the matrices
A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Element-wise multiplication
elementwise_product = np.multiply(A2, B2)

# Matrix multiplication
matrix_product = np.dot(A2.T, B2)

# Addition of both matrices
sum_of_matrices = np.add(A2, B2)

# Subtraction of matrix B from A
difference = np.subtract(A2, B2)

# Division of matrix B by A
division = np.divide(B2, A2)

print("Element-wise multiplication:\n", elementwise_product)
print("Matrix multiplication:\n", matrix_product)
print("Addition of both matrices:\n", sum_of_matrices)
print("Subtraction of matrix B from A:\n", difference)
print("Division of matrix B by A:\n", division)

Element-wise multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix multiplication:
 [[107 122 137 152]
 [122 140 158 176]
 [137 158 179 200]
 [152 176 200 224]]
Addition of both matrices:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Subtraction of matrix B from A:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Division of matrix B by A:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [20]:
#12. Which function in Numpy can be use^ to swap the byte or^er of an array?
'''
In NumPy, you can use the byteswap() method to swap the byte order of an array
This method toggles between low-endian and big-endian data representation
'''

'\nIn NumPy, you can use the byteswap() method to swap the byte order of an array\nThis method toggles between low-endian and big-endian data representation\n'

In [21]:
#13. What is the significance of the np.linalg.inv function?
'''
The np.linalg.inv function in NumPy is used to compute the (multiplicative) inverse of a square matrix. The multiplicative inverse of a matrix A is a matrix A_inv such that when A is
multiplied by A_inv, the result is the identity matrix.
'''

'\nThe np.linalg.inv function in NumPy is used to compute the (multiplicative) inverse of a square matrix. The multiplicative inverse of a matrix A is a matrix A_inv such that when A is \nmultiplied by A_inv, the result is the identity matrix.\n'

In [22]:
#14. What ^oes the np.reshape function ^o, an^ how is it use^?
'''
The np.reshape function in NumPy is used to change the shape of an array without modifying its data. The new shape should be compatible with the original shape. If an integer is
 passed as the new shape, then the result will be a 1-D array of that length. One shape dimension can be -1, in which case, the value is inferred from the length of the array and
 remaining dimensions
 '''

'\nThe np.reshape function in NumPy is used to change the shape of an array without modifying its data. The new shape should be compatible with the original shape. If an integer is\n passed as the new shape, then the result will be a 1-D array of that length. One shape dimension can be -1, in which case, the value is inferred from the length of the array and \n remaining dimensions\n '

In [23]:
#15. What is broa^casting in Numpy?
'''
Broadcasting in NumPy is a set of rules that allows arithmetic operations to be performed between arrays of different shapes. The term broadcasting describes how NumPy treats
arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible
shapes.

Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to
 efficient algorithm implementations.
'''

'\nBroadcasting in NumPy is a set of rules that allows arithmetic operations to be performed between arrays of different shapes. The term broadcasting describes how NumPy treats \narrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible\nshapes.\n\nBroadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to\n efficient algorithm implementations.\n'